#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
    # exec-once = nm-applet &
    # exec-once = waybar & hyprpaper & firefox

# Autostart applications and services
exec-once = waybar &           # Start the Waybar status bar
exec-once = nm-applet --indicator & # Start the network manager applet
exec-once = mako &              # Start the Mako notification daemon
exec-once = hypridle &
exec-once = hyprshot &
exec-once = hyprpaper -c ~/Pictures/wallpaper/Kath.png         # Start the Hyprpaper wallpaper utility
    #exec-once = your_terminal_app & # Start your preferred terminal emulator
